### ISSUE TITLE
Error Native module cannot be null

### ISSUE THREAD

**Issue by maurovisintin** [Figedi/react-native-soundboard#2]
Hi there, 
I followed all the instructions:
-clone repo
- npm install
- add assets library and adapt constants.js

but when i run-ios on simulator I get this 

<img width="283" alt="screen shot 2016-11-23 at 17 43 20" src="https://cloud.githubusercontent.com/assets/7148528/20570549/5770e10e-b1a4-11e6-95e7-e04e6082d374.png">

any clue?

**Comment by Figedi** [comment]
That seems like a linking issue, I'm guessing this is solved since you have already closed the issue.
